### ISSUE TITLE
Example project missing VideoTpl

### ISSUE THREAD

**Issue by andygrall** [swiftuiux/swiftui-video-player-example#1]
![Screenshot 2024-09-09 at 11 12 54 AM](https://github.com/user-attachments/assets/6be50919-e9fb-4870-87bf-925b853944b1)

I was trying to see how to use this code, but the example project won't run. Missing VideoTpl

**Comment by swiftuiux** [comment]
Thank you did not notice it
Updated
I’d appreciate it if you’d confirm that you managed to run

**Comment by andygrall** [comment]
Thanks for the quick reply. Yes, I'm able to run it now.
